name: 'Run SwiftLint with reviewdog'
description: '🐶 Run SwiftLint with reviewdog on pull requests to improve code review experience.'
author: '@nnsnodnb'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
    required: true
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'swiftlint'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
    required: true
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-check,github-pr-review].'
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog. Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  swiftlint_version:
    description: 'SwiftLint version to install'
    default: '0.63.2'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check'
  color: 'blue'
